#%RAML 1.0
title: Banking AISP Experience API
version: v1
baseUri: https://localhost:8082/api
mediaType: application/json
protocols: HTTPS

types: !include dataTypes.raml
securitySchemes: !include securitySchemes.raml
securedBy: [oauth_2_0]


/info:      
  displayName: Accounts information
  get:
    description: Retrieves information about the accounts authorized by the Customer.
    responses:
      200:
        body:
          application/json: 
            type: account[]
            example: !include examples/info-response.json 
              
/transactions:
  displayName: Accounts transactions
  get:
    description: Retrieves transactions for the accounts authorized by the Customer.
    responses:
      200:
        body:
          application/json:           
            type: accountTransaction[]
            example: !include examples/transactions-response.json

/balance:
  displayName: Accounts balance
  get:
    description: Retrieves balances for the accounts authorized by the Customer.
    responses:
      200:
        body:
          application/json:
            type: accountBalance[]
            example: !include examples/balance-response.json
