#%RAML 1.0
title: Banking_AISP_Experience_API
version: v2
baseUri: http://localhost:8081/api/
mediaType: application/json
protocols: [HTTPS]

uses: 
  aisp: dataTypes.raml

securitySchemes: 
  oAuth_2_0: !include securityScheme.raml

# Securing the API with Basic Authorization and OAuth 2.0
securedBy: [oAuth_2_0]

/info:
  get:
    description: Retrieves information about the accounts authorized by the Customer.
    displayName: Retrieve accounts information
    responses:
      200:
        body:
          application/json: 
            type: aisp.AccountAISP[]
            example: !include examples/info-response.json 
              
/transactions:
  get:
    description: Retrieves transactions for the accounts authorized by the Customer.
    displayName: Retrieve accounts transactions
    responses:
      200:
        body:
          application/json:           
            type: aisp.AccountTransaction[]
            example: !include examples/transactions-response.json

/balance:
  get:
    description: Retrieves balances for the accounts authorized by the Customer.
    displayName: Retrieve accounts balance
    responses:
      200:
        body:
          application/json:
            type: aisp.AccountBalanceAISP[]
            example: !include examples/balance-response.json